### ISSUE TITLE
Question on same-origin policy (SOP) across iframes

### ISSUE THREAD

**Issue by paragmajum** [kmikael/PBWebViewController#23]
Does `PBWebViewController`'s webkit implementation allow access to web preferences so that one can disable SOP across iframes that have different origins? Or is it just a view controller built over the standard iOS Webkit library?

**Comment by kmikael** [comment]
`PBWebViewController` is just a convenient view controller that wraps a `UIWebView`.

**Comment by paragmajum** [comment]
Thanks. Would you know how SOP can be disabled in iOS? I mean, is there a webkit implementation that you know of that allows this?

**Comment by kmikael** [comment]
Sorry. I don't know how it would work on iOS. Check out the `UIWebView` or the newer `WKWebView` documentation.
