### ISSUE TITLE
App stuck in Simulator and crash in Device

### ISSUE THREAD

**Issue by brbgyn** [kmikael/PBWebViewController#24]
Hi, the sample project crashes on Device and stuck in simulator, increasing Memory Usage, when opening the following webpage:

http://cbn.globoradio.globo.com/comentaristas/mauro-halfeld/2015/08/27/ONDE-FICA-O-FUNDO-DO-POCO-DESSA-CRISE.htm

What could it be ?

Thank you

**Comment by kmikael** [comment]
I really don't know. I couldn't reproduce the crash. It could be that the site uses to much memory or that the site itself has a JavaScript bug.

**Comment by brbgyn** [comment]
This websites also stuck the webview:

http://m.cbn.globoradio.globo.com/default_mobile.htm?url=/editorias/economia/2015/09/14/CORTES-NO-MINHA-CASA-MINHA-VIDA-VAO-GERAR-ECONOMIA-DE-R-48-BILHOES.htm

http://m.cbn.globoradio.globo.com/default_mobile.htm?url=/comentaristas/kennedy-alencar/2015/09/14/DILMA-ESTA-DANDO-SINAIS-DE-QUE-VAI-ERRAR-DE-NOVO.htm

Here is the link for the sample project with the problem:

https://www.dropbox.com/sh/e2nbmow6br20x2f/AADDECbeccIftb_cpL4XGxUja?dl=0

Just get the original project and in KMMasterViewController.m substitute:
```
- (NSArray *)bookmarks
{
    if (!_bookmarks) {
        _bookmarks = @[
            @"http://www.apple.com",
            @"http://daringfireball.net",
            @"http://www.macstories.net",
            @"http://www.macdrifter.com",
            @"http://brettterpstra.com",
            
            @"http://www.pinbrowser.co",
            @"http://kmikael.com",
            @"https://twitter.com/mkonutgan"
        ];
    }
    
    return _bookmarks;
}
```
for:
```
- (NSArray *)bookmarks
{
    if (!_bookmarks) {
        _bookmarks = @[
            @"http://m.cbn.globoradio.globo.com/default_mobile.htm?url=/editorias/economia/2015/09/14/CORTES-NO-MINHA-CASA-MINHA-VIDA-VAO-GERAR-ECONOMIA-DE-R-48-BILHOES.htm",
            @"http://cbn.globoradio.globo.com/comentaristas/mauro-halfeld/2015/08/27/ONDE-FICA-O-FUNDO-DO-POCO-DESSA-CRISE.htm",
            @"http://m.cbn.globoradio.globo.com/default_mobile.htm?url=/comentaristas/kennedy-alencar/2015/09/14/DILMA-ESTA-DANDO-SINAIS-DE-QUE-VAI-ERRAR-DE-NOVO.htm",
            @"http://www.macdrifter.com",
            @"http://brettterpstra.com",
            
            @"http://www.pinbrowser.co",
            @"http://kmikael.com",
            @"https://twitter.com/mkonutgan"
        ];
    }
    
    return _bookmarks;
}
```
And test it, please.

Thank you

**Comment by brbgyn** [comment]
Nobody ?

@kmikael ?

**Comment by kmikael** [comment]
All 3 links work for me on the iPhone and the iPad. What devices, operating system etc. are you using?

**Comment by kmikael** [comment]
On the iPad it always works. On the iPhone I can confirm that it gets stuck. I don't have an idea why at the moment.

**Comment by brbgyn** [comment]
Thanks @kmikael 

All 3 links open normally in another UIWebView i have in my app.

**Comment by brbgyn** [comment]
Doing some tests now i can see that sometimes it stucks, but sometimes not.

Strange behavior
