### ISSUE TITLE
support cache?

### ISSUE THREAD

**Issue by leancmscn** [kmikael/PBWebViewController#28]

**Comment by kmikael** [comment]
Hi, what do you mean by "support cache?"? Could you elaborate?

**Comment by leancmscn** [comment]
does PBWebViewController save content automaticly when viewing. then user can review them after close 3G.

**Comment by kmikael** [comment]
PBWebViewController uses the normal caching mechanisms of the foundation URL loading system.

You can set a custom `NSURLRequest` on an instance of `PBWebViewController` with the caching behavior you desire.
