### ISSUE TITLE
PBSafariActivity not in PBWebViewController Pod

### ISSUE THREAD

**Issue by markramrattan** [kmikael/PBWebViewController#30]
Via pod install PBSafariActivity isn't included. Would be great for an update. (will drag and drop manually). Or create an additional pod for it. 

Thank you, great work!

**Comment by kmikael** [comment]
The idea here is that each individual had different needs so I didn't include the PBSafariActivity, that's just an example. It's easy to just drag and drop it like you did or create your own activity.

There are also other pods that provide this: I just found [ARSafariActivity](https://cocoapods.org/pods/ARSafariActivity) for example
